version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: therapist-platform-rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest